### ISSUE TITLE
Not respecting  timeout

### ISSUE THREAD

**Issue by jaggedsoft** [request/request#2535]
Prior to my last npm update, timeout was working fine. Now it's completely ignoring whatever value I provide. Any ideas?
/proc/sys/net/ipv4/tcp_syn_retries is set to 3

Thanks for this awesome software!!

**Comment by talasila66** [comment]
Any update on the above issue, we are also facing similar issue?

**Comment by kristiansaarela** [comment]
Yes, I'm also experiencing same issue. Seems like timeout functionality broke in 2.76.0 release.

**test_timeout.js**
```js
var nock = require('nock')
var request = require('request')

nock('http://google.com').get('/').delay(1000).reply(200, 'ok')

request.get({
	url: 'http://google.com',
	timeout: 100
}, function (err, res, body) {
	if (err) {
		console.error(err)
	}
	else {
		console.log(res.statusCode, body)
	}
})
```

**Successful test in v2.75.0:**
`npm install request@2.75.0`
`node test_timeout.js`

```
{ Error: ETIMEDOUT
    at Timeout._onTimeout (C:\Users\kristian\tests\node_modules\request\request.js:759:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', connect: false }
```

**Failing in v2.76.0 and above:**
`npm install request@2.76.0`
`node test_timeout.js`

```
200 'ok'
```

**Comment by jaggedsoft** [comment]
@talasila66 the fix for me was `npm install request@2.65.0`
I tested request@2.81.0 and request@2.79.0 and could not trigger the errors:
Error: ETIMEDOUT
Error: ESOCKETTIMEDOUT

**Comment by talasila66** [comment]
Thanks for the reply @jaggedsoft will test with npm install request@2.65.0 will let you know the update on the same.

**Comment by addityasingh** [comment]
@talasila66 We are also having the same issue for request@2.74.0. Can you confirm which version you were seeing this problem on?

**Comment by talasila66** [comment]
@addityasingh Started Using request@2.81.0 no issues has been observed related to the timeout. Our issue is Exress JS Server has a default configuration of 2 mins response timeout, after that it started sending in complete response. 

Hence it looked like request@2.81.0 module not respecting the timeout. Solved by increasing Exress JS Server timeout parameter.

**Comment by addityasingh** [comment]
Thanks. But doesn't work for me on 2.81.0 or 2.74.0. I will try to check again with 2.81.0

**Comment by ayqy** [comment]
"request": "^2.81.0" has the same error
nginx proxy pass, node restarts many times due to this error, try request@2.65.0

**Comment by ayqy** [comment]
Unfoturnately, these timeout errors are still alive.
```
# cat /root/.pm2/logs/app-error-0.log
Error: ETIMEDOUT
    at Timeout._onTimeout (app/node/node_modules/request/request.js:808:15)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (app/node/node_modules/request/request.js:825:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.emitRequestTimeout (_http_client.js:614:42)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket.Socket._onTimeout (net.js:351:8)
    at ontimeout (timers.js:386:14)
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:581:26)
```
Is there a way to slove this? Or a solution to catch this? HELP!

**Comment by shuhei** [comment]
As far as I read the implementation, the `timeout` option is only applied to inactive socket by `request.setTimeout()` and the initial socket connection. It was introduced in https://github.com/request/request/commit/001eae3d479a13350b06b8d3f8182b2060a2c60d and v2.77.0, and was not fixed properly in https://github.com/request/request/commit/82da8b857050a7078a40b7e0f2781077c13abea7 v2.78.0.

If we make it compatible with the documentation, the timeout should be for request's `response` event. To do that, `timeoutTimer` has to be set regardless of `isConnecting`.

**Comment by shuhei** [comment]
Also, https://github.com/request/request/commit/1ef4075f5b649987b52cc71a1c33fdd8111d305c made the timeout cleared at socket connect event, which changed the behavior in the initial socket connection.

**Comment by jzastrow** [comment]
We also have problems with very slow long running requests, where the configured seems to be ignored after the first byte was sent. 
Is there a way to set a fixed timeout for the whole request cycle?

**Comment by jura-b** [comment]
Is this problem still persist?

**Comment by talasila66** [comment]
no

**Comment by kilianc** [comment]
I am still seeing this but only with node 10.7+

**Comment by aprilandjan** [comment]
Although `request` is not maintained any more, I'd say that this problem is still persist, in v2.88
